name:                katasRedux
version:             0.1.0.0
github:              "aesakamar/katasRedux"
license:             BSD3
author:              "Aesa Kamar"
maintainer:          "Aesa.Kamar@gmail.com"
copyright:           "???"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/aesakamar/katasRedux#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- contravariant
- cryptohash
- fixplate
- hscolour
- parsec
- parsec-numbers
- pretty-show
- split
- tasty
- tasty-hspec
- transformers-either

library:
  source-dirs: src

executables:
  katasRedux-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - katasRedux

tests:
  katasRedux-test:
    main:                Spec.hs
    source-dirs:         test, src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - katasRedux
